### ISSUE TITLE
Data is available on github

### ISSUE THREAD

**Issue by spraharsh** [parvmor/Student-Search-IITK#1]
I'm not very comfortable that my data is available with a simple search like [here](https://github.com/parvmor/Student-Search-IITK/blob/c52c87436f19a0339201da7c4236bc2d72b0733f/data/Students/Y12/12490/Summary)
why don't you see whether there's a way this information isn't available except on the IITK intranet. 
If I remember correctly it goes against the policies of the institute. 

people also tend to get spammy mails because their email ids are available. and it becomes easier to stalk by people outside

**Comment by parvmor** [comment]
I did not notice your issue and also did not remember that data was publicly available. Sorry for this. I have removed the data and all traces of it from the repo.
